# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

variables:
  # Container registry service connection established during pipeline creation
  imageRepository: 'sample'
  containerRegistry: 'kubernetedcontainer.azurecr.io'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'dockerregistryserviceconnection'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      inputs:
        command: 'buildAndPush'
        repository: $(imagerepository)
        Dockerfile: '**/Dockerfile'
        containerRegistry: 'dockerregistryserviceconnection'
        tags: 
          $(tag)

    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  -  deployment: 
     displayName: deploy to stage
     pool:
      vmImage: $(vmImageName)
     environment: 'k8sdev.default'
     strategy:
       runOnce:
         deploy:
           steps:
           - task: KubernetesManifest@1
             displayName:   create image pull secret
             inputs:
               action: 'createSecret'
               secretName: '$(imagePullSecret)'
               dockerRegistryEndpoint: 'dockerregistryserviceconnection'
           - task: KubernetesManifest@1
             inputs:
               action: 'deploy'
               connectionType: 'kubernetesServiceConnection'
               kubernetesServiceConnection: 'kubernetesserviceconnection'
               namespace: 'default'
               manifests: '$(Pipeline.Workspace)/manifests/deployment.yml $(Pipeline.Workspace)/manifests/service.yml'
               containers: '$(containerRegistry)/$(imageRepository):$(tag)'
               imagePullSecrets: '$(imagePullSecret)'

 